### PR TITLE
Multiple bugfixes

### LINKED ISSUE #5843: Dataset import fails (h-cls dataset, Datumaro v1) with unclear message
The same steps as in #5805
1. Prepare a datumaro dataset exported in Geti Classic for hierarchical classification.
2. Create a multi-label classification project. Add one label.
3.  Import the dataset.

The import fails. UI shows a nasty exception instead of a nice error message. If hierarchical classification is not supported, I'd expect a more user friendly error.
Backend shows:
```
  File "/application/backend/.venv/lib/python3.13/site-packages/datumaro/experimental/dataset.py", line 510, in __getitem__
    direct_attributes[key] = attr_info.field.from_polars(key, 0, row_df, attr_info.type)
    │                 │      │         │     │           │       │       │         └ <class 'int'>
    │                 │      │         │     │           │       │       └ AttributeInfo(type=<class 'int'>, field=LabelField(semantic='default', dtype=UInt8, multi_label=False, is_list=True), categor...
    │                 │      │         │     │           │       └ shape: (1, 4)
    │                 │      │         │     │           │         ┌─────────────┬─────────┬──────────┬─────────────────────────────────┐
    │                 │      │         │     │           │         │ image_info  ┆ subset  ┆ label    ┆ ima...
    │                 │      │         │     │           └ 'label'
    │                 │      │         │     └ <function LabelField.from_polars at 0x769e21c75080>
    │                 │      │         └ LabelField(semantic='default', dtype=UInt8, multi_label=False, is_list=True)
    │                 │      └ AttributeInfo(type=<class 'int'>, field=LabelField(semantic='default', dtype=UInt8, multi_label=False, is_list=True), categor...
    │                 └ 'label'
    └ {'image_path': '/application/data/staged_datasets/45a51860-2a24-40a6-bc1d-d9458d734768/dataset/images/image_path_000000.jpg',...
  File "/application/backend/.venv/lib/python3.13/site-packages/datumaro/experimental/fields/annotations.py", line 253, in from_polars
    return from_polars_data(data, target_type)
           │                │     └ <class 'int'>
           │                └ shape: (1,)
           │                  Series: '' [u8]
           │                  [
           │                    4
           │                  ]
           └ <function from_polars_data at 0x769fbee58b80>
  File "/application/backend/.venv/lib/python3.13/site-packages/datumaro/experimental/type_registry.py", line 263, in from_polars_data
    return _from_polars_converters[target_type](polars_data)
           │                       │            └ shape: (1,)
           │                       │              Series: '' [u8]
           │                       │              [
           │                       │                    4
           │                       │              ]
           │                       └ <class 'int'>
           └ {<class 'numpy.ndarray'>: <function <lambda> at 0x769fbee58540>, <class 'int'>: <function <lambda> at 0x769fbee585e0>, <class...
  File "/application/backend/.venv/lib/python3.13/site-packages/datumaro/experimental/type_registry.py", line 109, in <lambda>
    int: lambda x: int(x),
                │      └ shape: (1,)
                │        Series: '' [u8]
                │        [
                │               4
                │        ]
                └ shape: (1,)
                  Series: '' [u8]
                  [
                        4
                  ]

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Series'
```

### PR DESCRIPTION
**Pull request by jpggvilaca**
### Summary

* Fixes https://github.com/open-edge-platform/training_extensions/issues/5843
* Ran knip to clear deadcode
* Update inference canvas rows (potential fix for tauri app resize issue)

Screenshot 2026-04-14 at 16 47 35
Screenshot 2026-04-14 at 16 47 41

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/components/job-status-card/job-status-card.component.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ type JobStatusCardProps = {
     title: string;
     message?: string;
     bottomIcon?: ReactNode;
-    bottomLeftMessage: string;
+    bottomLeftMessage: ReactNode;
     bottomRightMessage?: string;
     actionButtons: ReactNode;
```
[the remark this answers is not in the document]
Comment (jpggvilaca) [reply application/ui/src/components/job-status-card/job-status-card.component.tsx:16]: Updated

File: application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx [hunk 2]
```diff
@@ -26,9 +44,7 @@ export const ImportFailedJob = ({
 }: ImportFailedJobProps) => {
     const deleteFileMutation = useDeleteStagedDataset({ stagedDatasetId, deleteEntry });
 
-    const handleClose = () => {
-        deleteFileMutation.mutate();
-    };
+    const errorMessage = message ?? 'An unknown error occurred';
```
[the remark this answers is not in the document]
Comment (jpggvilaca) [reply application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx]: Updated

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts [hunk 3]
```diff
@@ -93,22 +93,16 @@ const useEncodingQuery = (
...
-
-            return executeWithTimeout(model.processEncoder(image), 'SAM encoder', SAM_TIMEOUT_MS);
-        },
-        staleTime: Infinity,
-        gcTime: 3600 * 15,
-        enabled: isEnabled,
-    });
+    return useQuery(
+        mediaItem !== undefined && image !== undefined
+            ? segmentAnythingEncodingQueryOptions(mediaItem, model, image, isEnabled)
```
Comment (dwesolow) [inline application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:98]: what was the issue here?

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts [hunk 4]
```diff
@@ -71,7 +71,7 @@ export const segmentAnythingEncodingQueryOptions = (
                 throw new Error('Model not yet initialized');
             }
 
-            return model.processEncoder(image);
+            return executeWithTimeout(model.processEncoder(image), 'SAM encoder', SAM_TIMEOUT_MS);
```
Comment (dwesolow) [inline application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:74]: what was the issue here?

File: application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx [hunk 5]
```diff
@@ -16,6 +18,22 @@ type ImportFailedJobProps = {
     deleteEntry: () => void;
 };
 
+const TechnicalDetails = ({ error }: { error: string }) => (
+    <details className={classes.details} aria-label={'Technical details of the job failure'}>
```
Comment (dwesolow) [inline application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx:22]: why not to use https://react-spectrum.adobe.com/v3/Disclosure.html?

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts (hunk 4 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:74]: We added §executeWithTimeout§ on other SAM calls, such as model.init. We forgot to add it here.

File: application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx (hunk 5 above)
Comment (jpggvilaca) [reply application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx:22]: I thought about it but went with a native approach. Do you think Disclosure would be better?

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts (hunk 3 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:98]: it was duplicated. segmentAnythingEncodingQueryOptions contains exactly the same as what was deleted

File: application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx (hunk 5 above)
Comment (dwesolow) [reply application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx:22]: Yeah, why not. Benefit of that would be that you don't need custom styles.

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts [hunk 6]
```diff
@@ -93,22 +93,16 @@ const useEncodingQuery = (
...
-        staleTime: Infinity,
-        gcTime: 3600 * 15,
-        enabled: isEnabled,
-    });
+    return useQuery(
+        mediaItem !== undefined && image !== undefined
+            ? segmentAnythingEncodingQueryOptions(mediaItem, model, image, isEnabled)
+            : {
+                  queryKey: ['segment-anything-model', 'encoding', 'disabled'] as const,
+                  queryFn: skipToken,
```
Comment (dwesolow) [inline application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:101]: This branch should never be called, right? I mean we're missing `enabled` here.

Comment (jpggvilaca) [reply application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:101]: Correct, enabled would be §false§ here. i went with https://tanstack.com/query/latest/docs/framework/react/guides/disabling-queries skipToken approach

File: application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx (hunk 5 above)
Comment (jpggvilaca) [reply application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx:22]: Tried. looks horrible and requires way more customisation ^^

Comment (dwesolow) [reply application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx:22]: Could u share the screenshot?

File: application/ui/src/components/job-status-card/job-status-card.component.tsx [hunk 7]
```diff
@@ -49,7 +49,7 @@ export const JobStatusCard = ({
                 <Flex alignItems='center' gap='size-100'>
                     {bottomIcon}
 
-                    <Text>{bottomLeftMessage}</Text>
+                    {isNonEmptyString(bottomLeftMessage) ? <Text>{bottomLeftMessage}</Text> : bottomLeftMessage}
```
Comment (camiloHimura) [inline application/ui/src/components/job-status-card/job-status-card.component.tsx:52]: 👍🏼

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts [hunk 8]
```diff
@@ -93,22 +93,16 @@ const useEncodingQuery = (
...
+                  staleTime: Infinity,
```
Comment (camiloHimura) [inline application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:102]: Can `staleTime` and `gcTime` be omitted?

Comment (jpggvilaca) [reply application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:102]: I guess so, yes

File: application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx (hunk 5 above)
Comment (jpggvilaca) [reply application/ui/src/components/import-card-status/import-failed-job/import-failed-job.component.tsx:22]: Reverted all my changes 😭  you gotta trust me lloolol

**Review by dwesolow — APPROVED** [review]

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts (hunk 8 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/tools/segment-anything-tool/use-segment-anything.hook.ts:102]: Ill get rid of them on my next PRs
