### PR TITLE
fix: Display augmentation parameters when dependent parameter does not exist

### LINKED ISSUE #6132: Missing augmentation options
**Steps to reproduce**

1. Open the demo detection project
2. Click 'Train model'
3. Click 'Advanced settings'
4. Scroll down to the augmentation parameters

**Expected**

The augmentation parameters are correctly displayed and the user can configure them.

**Actual**

The augmentation section is unexpectedly empty.

Image

### PR DESCRIPTION
**Pull request by dwesolow**
### Summary

The issue was that implementation assumed that we always have dependent parameter. That was wrong assumption and this PR fixes that.

Fix #6132 

### Checklist

- [X] The PR title and description are clear and descriptive
- [X] I have manually tested the changes
- [X] All changes are covered by automated tests
- [X] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/models/train-model/advanced-settings/utils.ts [hunk 1]
```diff
@@ -101,40 +101,39 @@ export const isBoolEnableParameterGroup = (
...
-
-                    if (Array.isArray(dependsOnValue)) {
-                        return dependsOnValue.includes(curr.value);
-                    }
-
-                    return dependsOnValue === curr.value;
-                });
-
-                acc.push([curr, ...parametersDependingOnCurr]);
+    return parameters.reduce<TrainingConfigurationParameter[]>((acc, curr, _idx, parametersOnTheSameDepth) => {
```
Comment (jpggvilaca) [inline application/ui/src/features/models/train-model/advanced-settings/utils.ts:121]: Can we add a comment on this routine? I cannot comprehend what is going on here but i trust your implementation since you also add tests. Let's just add a comment so the next engineer understands what is being done here. Also, np: `!=` -> `!==` : )

Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/utils.ts:121]: If I replace to `!==` I would need to do `parameter !== undefined && parameter !== null`, shorthand is `parameter != null`.

Comment (ActiveChooN) [reply application/ui/src/features/models/train-model/advanced-settings/utils.ts:121]: `!isNil` from lodash?

File: application/ui/src/features/models/train-model/advanced-settings/utils.ts [hunk 2]
```diff
@@ -101,40 +101,39 @@ export const isBoolEnableParameterGroup = (
...
+        if (curr.depends_on != null) {
+            const dependentParameter = parametersOnTheSameDepth.find(
+                (parameter) => curr.depends_on != null && curr.depends_on[parameter.key] != null
```
Comment (ActiveChooN) [inline application/ui/src/features/models/train-model/advanced-settings/utils.ts:124]: Why is an extra `curr.depends_on != null` needed here if it was already checked in the previous condition?

File: application/ui/src/features/models/train-model/advanced-settings/utils.ts (hunk 1 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/utils.ts:121]: why to use lodash for such simple thing?

File: application/ui/src/features/models/train-model/advanced-settings/utils.ts (hunk 2 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/utils.ts:124]: TypeScript's type narrowing doesn't carry into callback functions passed to methods like .find(). Inside the callback, TypeScript can no longer guarantee that curr.depends_on hasn't changed since the null check on line 105, so it widens the type back to include null | undefined.

File: application/ui/src/features/models/train-model/advanced-settings/utils.ts (hunk 1 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/utils.ts:121]: Updated

**Review by jpggvilaca — DISMISSED** [review]

**Review by ActiveChooN — DISMISSED** [review]

**Review by jpggvilaca — APPROVED** [review]
