### PR TITLE
fix: Flickering SAM tool

### LINKED ISSUE #5854: [UI] App flickering during SAM annotation
STR
1. Run Windows App
2. Create Detection project -> upload media
3. Start Annotations with SAM -> UI flickering

### PR DESCRIPTION
**Pull request by dwesolow**
### Summary

Close #5854 

### Checklist

- [X] The PR title and description are clear and descriptive
- [X] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/annotator/tools/segment-anything-tool/use-with-cancel.ts [hunk 1]
```diff
@@ -16,12 +16,14 @@ export const useWithCancel = (fn: (points: InteractiveAnnotationPoint[]) => Prom
 
             abortController.current = new AbortController();
 
-            const result = await fn(...args);
+            const fnResult = fn(...args);
```
Comment (jpggvilaca) [inline application/ui/src/features/annotator/tools/segment-anything-tool/use-with-cancel.ts]: why this change?

Comment (dwesolow) [reply application/ui/src/features/annotator/tools/segment-anything-tool/use-with-cancel.ts]: reverted

**Review by jpggvilaca — APPROVED** [review]
Still unsure if this will affect performance, but let's fix this for now
