### PR TITLE
fix: Display device type and if available index and memory

### LINKED ISSUE #6129: Select training device dropdown doesn't render all available options
**Describe the bug**

Different devices of the same type are filtered in "Select training device" dropdown:

Image

Recommendation is to distinguish dropdown items by both `type` and `index`.

**Steps to Reproduce**

1. Run Geti app on env with 2 cuda cards.
2. Open training dialog.
3. Click on "Select training device" dropdown.

**Expected:** both cuda cards available in options
**Actual:** only one cuda card is available

### PR DESCRIPTION
**Pull request by dwesolow**
### Summary

image

Fix #6129 

### Checklist

- [X] The PR title and description are clear and descriptive
- [X] I have manually tested the changes
- [X] All changes are covered by automated tests
- [X] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
+// Copyright (C) 2025 Intel Corporation
+// SPDX-License-Identifier: Apache-2.0
+
+import { Item, Picker } from '@geti/ui';
+
+import type { TrainingDevice } from '../../../../constants/shared-types';
+import { createTrainingDeviceKey, useTrainModelState } from '../train-model-provider.component';
+
+const formatTrainingDeviceMemory = (bytes: number): string => {
```
Comment (jpggvilaca) [inline application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx:9]: we could leverage `pretty-bytes` here. We have it on shared utils

File: application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    return `${Math.ceil(bytes / 1024 ** 3)} GB`;
+};
+
+const createTrainingDeviceName = (trainingDevice: TrainingDevice): string => {
+    let name: string = trainingDevice.name;
```
Comment (jpggvilaca) [inline application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx]: can we not omit this `: string` here?

File: application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx (hunk 1 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx:9]: We cannot since we always want to round up and use 1024 not 1000 as unit (jedec standard), discussed that with Leo.

File: application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx (hunk 2 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx]: probably yes

File: application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+
+    return name;
+};
+
+export const SelectTrainingDevice = () => {
+    const { trainingDevices, onSelectTrainingDevice, selectedTrainingDevice } = useTrainModelState();
+
+    return (
+        <Picker
+            flex={1}
```
[the remark this answers is not in the document]
Comment (dwesolow) [reply application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx:33]: not valid

File: application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+import type { TrainingDevice } from '../../../../constants/shared-types';
+import { createTrainingDeviceKey, useTrainModelState } from '../train-model-provider.component';
+
+const formatTrainingDeviceMemory = (bytes: number): string => {
+    return `${Math.ceil(bytes / 1024 ** 3)} GB`;
+};
+
+const createTrainingDeviceName = (trainingDevice: TrainingDevice): string => {
+    let name: string = trainingDevice.name;
+
```
[the remark this answers is not in the document]
Comment (dwesolow) [reply application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx:15]: updated

File: application/ui/src/features/models/train-model/train-model-provider.component.tsx [hunk 5]
```diff
@@ -30,8 +30,8 @@ export type TrainModelContextProps = {
     onSelectModelArchitectureId: (id: string | null) => void;
 
     trainingDevices: TrainingDevice[];
-    selectedTrainingDevice: DeviceType | null;
-    onSelectTrainingDevice: (deviceType: DeviceType | null) => void;
+    selectedTrainingDevice: string | null;
+    onSelectTrainingDevice: (deviceType: string | null) => void;
```
[the remark this answers is not in the document]
Comment (dwesolow) [reply application/ui/src/features/models/train-model/train-model-provider.component.tsx]: updated

File: application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx (hunk 2 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/select-training-device/select-training-device.component.tsx]: updated

**Review by jpggvilaca — APPROVED** [review]
