### PR TITLE
Bug fixes for project creation & layout updates

### LINKED ISSUE #6189: With several project Add project area blended with list
1. Create several project.
2. Ensure you have that many projects that a scroll appears on the list shown after clicking on the project's name.

The icon and text Add project is blended with the list as can be seen below:
Image

Only when scrolled down, the area is back visible as shown below:
Image

### LINKED ISSUE #6190: Existing name suggested when creating projects from dataset
The same as #5823 but for the path: Create project / Create from dataset.

1. Create three projects using their default names (Project # 1, Project # 2, Project # 3).
2. Delete Project # 2.
3. Create a new project via Create project / Create from dataset.

The app suggests Project # 3 and displays an error beneath the edit box: "That project name already exists".
I'd expect the app to look for an available name, or not to suggest anything.

### PR DESCRIPTION
**Pull request by jpggvilaca**
### Summary

* Closes https://github.com/open-edge-platform/training_extensions/issues/6189
* Closes https://github.com/open-edge-platform/training_extensions/issues/6190
* Solves an issue with validation when creating a project. `useCreateProject` invalidates /api/projects so when we create a project, even with an unique name, the error "Project with name X already exists" flashed for a second
* Improve export job details layout
* Model training parameters "boxes" should now have all the same height regardless of the number of params

Screenshot 2026-04-21 at 11 13 58
Screenshot 2026-04-21 at 11 36 27

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.component.tsx [hunk 1]
```diff
@@ -26,30 +26,44 @@ export const ExportJobDetails = ({ datasetName, metadata }: ExportJobDetailsProp
...
                 <Divider orientation='vertical' size='S' />
 
-                <Text UNSAFE_style={{ overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis' }}>
-                    With labels: {labelsList.join(', ')}
-                </Text>
+                <Flex alignItems={'center'} gap={'size-100'} minWidth={0}>
+                    <Text>Labels:</Text>
+                    <Flex gap={'size-75'} wrap UNSAFE_style={{ minWidth: 0, overflow: 'hidden' }}>
+                        {labelsList.map((label) => (
+                            <Badge variant={'neutral'} key={label}>
```
Comment (dwesolow) [inline application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.component.tsx]: if the color is available we could use the color of the label as the background color of the badge.

**Review by dwesolow — DISMISSED** [review]

File: application/ui/src/features/project/create/create-project-form.tsx [hunk 2]
```diff
@@ -37,10 +37,14 @@ export const CreateProjectForm = ({ projects }: CreateProjectFormProps) => {
...
-        projects.map((project) => project.name)
-    );
+    const isSubmitting = createProjectMutation.isPending || createProjectMutation.isSuccess;
+
+    const validationErrorMessage = isSubmitting
+        ? undefined
+        : validateProjectName(
+              name,
+              projects.map((project) => project.name)
+          );
```
[the remark this answers is not in the document]
Comment (jpggvilaca) [reply application/ui/src/features/project/create/create-project-form.tsx:47]: Updated

File: application/ui/tests/datasets/export-dataset.spec.ts [hunk 3]
```diff
@@ -119,9 +119,10 @@ test.describe('Export dataset', () => {
 
         await test.step('Verify export job progress', async () => {
             await expect(dialog).toBeHidden();
-            await expect(
-                page.getByText(`With labels: ${projectLabels.map((label) => label.name).join(', ')}`)
-            ).toBeVisible();
+            await expect(page.getByText('Labels:')).toBeVisible();
+            for (const label of projectLabels) {
+                await expect(page.getByText(label.name, { exact: true })).toBeVisible();
+            }
```
[the remark this answers is not in the document]
Comment (jpggvilaca) [reply application/ui/tests/datasets/export-dataset.spec.ts]: Updated

File: application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.component.tsx (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.component.tsx]: I reverted, i think i would have to also update on project card on projects page. So ill just leave the strings for now

File: application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.test.tsx [hunk 4]
```diff
@@ -94,7 +100,7 @@ describe('ExportJobDetails', () => {
 
         renderApp(metadata);
 
-        expect(await screen.findByText('Only media with annotations')).toBeVisible();
+        expect(await screen.findByText(/Only media with annotations/)).toBeVisible();
```
Comment (camiloHimura) [inline application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.test.tsx:98]:
```suggestion
        expect(await screen.findByText(/Only media with annotations/i)).toBeVisible();
```

File: application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.test.tsx [hunk 5]
```diff
@@ -109,6 +115,6 @@ describe('ExportJobDetails', () => {
 
         await screen.findByText('COCO');
 
-        expect(await screen.findByText('All media')).toBeVisible();
+        expect(await screen.findByText(/All media/)).toBeVisible();
```
Comment (camiloHimura) [inline application/ui/src/features/dataset/import-export/export-jobs-list/export-job/export-details/export-details.test.tsx:113]:
```suggestion
        expect(await screen.findByText(/All media/i)).toBeVisible();
```

**Review by dwesolow — DISMISSED** [review]

**Review by dwesolow — APPROVED** [review]
