### PR TITLE
Miscellaneous fixes

### LINKED ISSUE #5496: [UI] Disable creating a pipeline on edge cases
Cases:
1) Sink/source are not set up
2) Project already has a pipeline running

Relates to #5494

### LINKED ISSUE #5557: Training progress shows limited increase
The numbers below for Mask_RCNN-EfficientNet-B2 but the same observations for all the models.
Two issues:
1. Once the training starts, the jobs endpoint starts reporting a progress of ~15%.
Then, for the 13 minutes for this particular job, the reported progress grew slowly till ~25%.
Then, it went to 100% and the training finished just seconds afterwards.
I'd expect more distributed values for the range 0 - 100%.
2. The elapsed time is not reported in the UI. See the screenshot below:
Image

### LINKED ISSUE #5592: Expose option to limit number of collected items in the UI
The server allows to optionally specify a maximum number of dataset items that can be collected by the data collection policies.

Image

This ticket is about exposing that option in the UI.

### PR DESCRIPTION
**Pull request by jpggvilaca**
### Summary

Closes a few from https://github.com/open-edge-platform/training_extensions/issues/5532, https://github.com/open-edge-platform/training_extensions/issues/5557 , https://github.com/open-edge-platform/training_extensions/issues/5496 , https://github.com/open-edge-platform/training_extensions/issues/5592
1 fix per commit, a few screenshots:

Screenshot 2026-02-25 at 13 22 56
Screenshot 2026-02-25 at 13 08 11
Screenshot 2026-02-25 at 12 42 23
Screenshot 2026-02-25 at 12 36 46
Screenshot 2026-02-25 at 14 51 24

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/inference/aside/data-collection.component.tsx [hunk 1]
```diff
@@ -60,14 +61,37 @@ export const DataCollection = () => {
...
+                </Heading>
+
+                <Text marginY={'size-100'}>Maximum number of items to collect</Text>
+
+                <NumberField
+                    label={'Size'}
+                    width={'100%'}
+                    minValue={1}
+                    step={1}
+                    value={localMaxDatasetSize}
```
Comment (dwesolow) [inline application/ui/src/features/inference/aside/data-collection.component.tsx]: why do we need local state if each change we send the update request?

File: application/ui/src/features/inference/aside/data-collection.component.tsx [hunk 2]
```diff
@@ -91,7 +114,7 @@ export const DataCollection = () => {
                     onChange={setLocalRate}
                     onChangeEnd={(rate) => updatePolicies({ rate })}
                     label='Rate'
-                    isDisabled={isDisabled || !ratePolicy?.enabled}
+                    isDisabled={!ratePolicy?.enabled}
```
Comment (dwesolow) [inline application/ui/src/features/inference/aside/data-collection.component.tsx]: if `updatePolicies` took longer and we changed the value here, it would cause unexpected behavior, no?

File: application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx [hunk 3]
```diff
@@ -93,6 +93,18 @@ export const TrainingModelRow = ({
...
+    useEffect(() => {
+        if (!job.started_at || job.status !== 'RUNNING') {
+            return;
+        }
+
+        const timeoutId = setInterval(() => setTick((v) => v + 1), 1000);
+
+        return () => clearInterval(timeoutId);
+    }, [job.started_at, job.status]);
+
```
Comment (dwesolow) [inline application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx]: Could u explain why we need this?

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.tsx [hunk 4]
```diff
@@ -29,16 +34,36 @@ export const TogglePipelineButton = () => {
...
-        </Button>
+        <>
+            <Button
+                isPending={disablePipelineMutation.isPending || enablePipelineMutation.isPending}
+                onPress={handleToggle}
+            >
+                {isPipelineEnabled ? 'Disable' : 'Enable'} Pipeline
+            </Button>
+
+            <DialogContainer onDismiss={() => setIsEnableBlockedDialogOpen(false)}>
```
Comment (dwesolow) [inline application/ui/src/features/inference/header/toggle-pipeline-button.component.tsx]: This component is duplicated in other places, could we reuse that?

File: application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx (hunk 3 above)
Comment (jpggvilaca) [reply application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx]: To update the elapsed time every second. We compute this based on started_at, which never changes (even if we get job status updates through SSE)

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.tsx (hunk 4 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/header/toggle-pipeline-button.component.tsx]: I thought about it, since it's used on this button and menu actions, but not sure if it's worth since i dont think they will be used anywhere else, but i guess since im pushing an extra commit i can move it to shared.

File: application/ui/src/features/inference/aside/data-collection.component.tsx (hunk 2 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/aside/data-collection.component.tsx]: what do you mean exactly?

File: application/ui/src/features/inference/aside/data-collection.component.tsx (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/aside/data-collection.component.tsx]: indeed, not being a slider i guess we dont need the local and can just make this numberfield fully controlled.

File: application/ui/src/features/project/list/menu-actions/menu-actions.component.tsx [hunk 5]
```diff
@@ -16,18 +16,22 @@ import classes from './menu-actions.module.scss';
 type MenuActionsProps = {
     projectId: string;
     projectName: string;
-    activePipeline?: boolean;
+    pipelineState?: {
+        isRunning: boolean;
+        isConfigured?: boolean;
```
Comment (dwesolow) [inline application/ui/src/features/project/list/menu-actions/menu-actions.component.tsx]: Is that set anywhere? I see only `isRunning` is set.

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+import { render } from 'test-utils/render';
+
+import { http } from '../../../api/utils';
+import { server } from '../../../msw-node-setup';
+import { queryClient } from '../../../query-client/query-client';
+import { TogglePipelineButton } from './toggle-pipeline-button.component';
+
+describe('TogglePipelineButton', () => {
+    beforeEach(() => {
+        queryClient.removeQueries();
```
Comment (dwesolow) [inline application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx:16]: :(
We need to update `render` to accept query client and if not passed, create a new one on the fly (then each time when we call `render` we have a new instance of that and we don't need hacky solutions).

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+    });
+
+    it('enables pipeline when currently idle', async () => {
+        let currentStatus: 'idle' | 'running' = 'idle';
```
Comment (dwesolow) [inline application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx]: it's not used in expects, do we want to check that?

File: application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx (hunk 3 above)
Comment (dwesolow) [reply application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx]: Hmm, that's weird to do. Could we just display when job has started, without elapsed? I think it's easy for the user to see the time differences.

File: application/ui/src/features/inference/aside/data-collection.component.tsx (hunk 2 above)
Comment (dwesolow) [reply application/ui/src/features/inference/aside/data-collection.component.tsx]: if the `updatePolicies` is still running, we don't block other fields that could run that method, e.g. `Rate` field.

File: application/ui/src/components/add-media-button/add-media-button.component.test.tsx [hunk 8]
```diff
@@ -21,4 +21,15 @@ describe('AddMediaButton', () => {
...
     });
+
+    it('sets the expected accepted file extensions', () => {
+        render(<AddMediaButton onFilesSelected={vi.fn()} />);
+
+        const input = screen.getByLabelText(/Upload media files/);
+
+        expect(input).toHaveAttribute(
+            'accept',
+            '.mp4,.avi,.mkv,.mov,.webm,.m4v,.jpg,.jpeg,.png,.jfif,.tif,.tiff,.webp,.bmp'
```
Comment (camiloHimura) [inline application/ui/src/components/add-media-button/add-media-button.component.test.tsx]: It can use `VALID_IMAGE_EXT.join(',')` so that if we add or remove any elements, the test won’t break.

File: application/ui/src/features/inference/aside/sidebar-tabs.component.tsx [hunk 9]
```diff
@@ -52,16 +52,18 @@ const SidebarTabs = ({ tabs, selectedTab }: TabProps) => {
...
-                            key={label}
-                            isQuiet
-                            isSelected={label === tab}
-                            onChange={() => handleSetTab(label)}
-                            UNSAFE_className={styles.toggleButton}
-                            aria-label={`Toggle ${label} tab`}
-                        >
-                            {icon}
-                        </ToggleButton>
+                        <TooltipTrigger key={label} placement={'left'}>
```
Comment (camiloHimura) [inline application/ui/src/features/inference/aside/sidebar-tabs.component.tsx:55]: I thought we preferred contextual help over tooltips

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx (hunk 6 above)
Comment (camiloHimura) [reply application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx:16]: +10, I’ve had some tests fail due to query reuse.

File: application/ui/src/features/inference/aside/sidebar-tabs.component.tsx (hunk 9 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/aside/sidebar-tabs.component.tsx:55]: we do but in this case it's a tab, which is only an icon, so it would look weird an icon followed by another info icon

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx (hunk 6 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx:16]: We use this throughout the project, this and `queryClient.clear`. In any case, i agree and i have the changes locally. Will open a different PR for this

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx (hunk 7 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx]: True, let me remove it and hardcode the string on the payload

File: application/ui/src/features/inference/aside/data-collection.component.tsx (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/aside/data-collection.component.tsx]: Updated

File: application/ui/src/features/inference/aside/data-collection.component.tsx (hunk 2 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/aside/data-collection.component.tsx]: Updated

File: application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx (hunk 3 above)
Comment (jpggvilaca) [reply application/ui/src/features/models/model-listing/current-model-training/training-model-row.component.tsx]: Not weird, but i agree that it's overkill for such a metric. I removed the 'elapsed' altogether

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.tsx (hunk 4 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/header/toggle-pipeline-button.component.tsx]: Updated

File: application/ui/src/features/project/list/menu-actions/menu-actions.component.tsx (hunk 5 above)
Comment (jpggvilaca) [reply application/ui/src/features/project/list/menu-actions/menu-actions.component.tsx]: The idea was to be versatile and make these 2 distinctions. But since we're checking if the pipeline is configured directly on the consumer, this is not needed.

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx (hunk 7 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx]: Updated

File: application/ui/src/components/add-media-button/add-media-button.component.test.tsx (hunk 8 above)
Comment (jpggvilaca) [reply application/ui/src/components/add-media-button/add-media-button.component.test.tsx]: Updated

File: application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx (hunk 6 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/header/toggle-pipeline-button.component.test.tsx:16]: https://github.com/open-edge-platform/training_extensions/pull/5626

File: application/ui/src/features/inference/aside/data-collection.component.tsx [hunk 10]
```diff
@@ -60,14 +62,37 @@ export const DataCollection = () => {
         });
     };
 
-    const isDisabled = patchPipelineMutation.isPending || !canEditPipeline;
-
     return (
-        <Flex key={`${serverRate}-${serverConfidenceThreshold}`} direction={'column'} minHeight={0} height={'100%'}>
+        <Flex
+            key={`${maxDatasetSize}-${serverRate}-${serverConfidenceThreshold}`}
```
Comment (dwesolow) [inline application/ui/src/features/inference/aside/data-collection.component.tsx:67]: why do we need `key` here?

File: application/ui/src/features/inference/aside/data-collection.component.tsx [hunk 11]
```diff
@@ -60,14 +62,37 @@ export const DataCollection = () => {
...
+                <Text marginY={'size-100'}>Maximum number of items to collect</Text>
+
+                <NumberField
+                    label={'Size'}
+                    width={'100%'}
+                    minValue={1}
+                    step={1}
+                    value={maxDatasetSize}
+                    onChange={(nextMaxDatasetSize) => {
+                        updatePolicies({ maxDatasetSize: nextMaxDatasetSize });
```
Comment (dwesolow) [inline application/ui/src/features/inference/aside/data-collection.component.tsx:89]: I'm wondering about using debounce (to avoid spamming the server), thoughts?

**Review by dwesolow — APPROVED** [review]

File: application/ui/src/features/inference/aside/data-collection.component.tsx (hunk 10 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/aside/data-collection.component.tsx:67]: No clue tbh, but will remove on next PR

File: application/ui/src/features/inference/aside/data-collection.component.tsx (hunk 11 above)
Comment (jpggvilaca) [reply application/ui/src/features/inference/aside/data-collection.component.tsx:89]: I checked. Experience is horrible. Let the server buuuuuurn. I also dont think the user will press the up/down hundreds of times.
