### PR TITLE
Removing a label should preserve annotation but disable Submit button

### LINKED ISSUE #6233: UI allows to send invalid annotation
**Describe the bug**

User has one annotation, assigns a label to the annotation, then clicks on X (next to the label name), "No label" appeared. Then user clicks "Submit". When opening back that image user sees there is a "No object" label for that image.
Expected: User should not be able to submit annotation without the label.
Actual: User is able to submit invalid annotation.

**Steps to Reproduce**

1. Create project, upload media.
2. Annotated, assign a label and then click X next to the label name to remove it.
3. Click submit.

### PR DESCRIPTION
**Pull request by jpggvilaca**
### Summary

* Closes https://github.com/open-edge-platform/training_extensions/issues/6233

Screenshot 2026-04-23 at 10 58 54

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

**Comment by dwesolow** [comment]
IMO we should not remove that annotation but we should disable the submit button so user cannot submit annotation with empty labels.

**Comment by jpggvilaca** [comment]
> IMO we should not remove that annotation but we should disable the submit button so user cannot submit annotation with empty labels.

I agree. Updated behavior and added screenshot

File: application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx [hunk 1]
```diff
@@ -38,16 +35,8 @@ export const AnnotationShapeWithLabels = ({ annotation }: AnnotationShapeProps)
         }
 
         const updatedLabels = annotation.labels.filter((label) => label.id !== labelId) as Label[];
-        const hasNoLabels = updatedLabels.length === 0;
-        const shouldDeleteAnnotation =
```
Comment (dwesolow) [inline application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx:42]: why do we need to touch anything here?

File: application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx [hunk 2]
```diff
@@ -68,7 +68,7 @@ export const SecondaryToolbar = ({
     const videoPlayerContext = useVideoPlayerContext();
     const isPlaying = videoPlayerContext?.videoControls?.isPlaying ?? false;
 
-    const { canSubmit, isSaving, submitAnnotations } = useAnnotationActions();
+    const { canSubmit, isSaving, submitAnnotations, hasInvalidAnnotation } = useAnnotationActions();
```
Comment (dwesolow) [inline application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx]: `hasInvalidAnnotation` is already in `canSubmit`, we don't need that here

File: application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx:42]: Because now we dont delete labels anymore

File: application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx (hunk 2 above)
Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx]: True, removed

File: application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx (hunk 1 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx:42]: But if we have global ones we want

Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx:42]: why should the behavior be different?

Comment (dwesolow) [reply application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx:42]: I've just tested it, I thought that would work a differently but is fine.
Tho I found one issue in multi class:

Image

Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx:42]: on, nice! ok, let me fix this one

Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/annotation-shape-with-labels.component.tsx:42]: Good catch, can you retest?

**Review by camiloHimura — APPROVED** [review]
