### PR TITLE
fix: Float range parameter respects min and max parameter value

### LINKED ISSUE #6093: Wrong rendering of float range parameters
**Steps to reproduce**

1. Open a detection project
2. Click 'Train model'
3. Select D-FINE-M or another model
4. Open 'Advanced settings' and go to the augmentation parameters

**Expected**

Float range parameters such as `color_jitter.brightness_range` are not constrained: the user can specify any value for the left (min) and right (max) bounds, unless `min_value` and/or `max_value` are provided. Also, the minimum must be always less or equal than the maximum.

For example, the user should be able to set the range to [0.5, 3].

**Actual**

The values are constrained between the defaults provided by the server, in this case 0.875 and 1.125. The user can't set values outside of this range, not even through the input field.

Image

### PR DESCRIPTION
**Pull request by dwesolow**
### Summary

This fixes float range parameter boundaries. Previously (based on geti classic implementation) we used default values as boundaries but that is no longer the case. We want to use `max_value` and `min_value` provided by the server.

Server change will be made in https://github.com/open-edge-platform/training_extensions/issues/6094. Either in server PR or in the follow up to that PR we will need to uncomment the code that uses `max_value` and `min_value`.

Fix #6093 

### Checklist

- [X] The PR title and description are clear and descriptive
- [X] I have manually tested the changes
- [X] All changes are covered by automated tests
- [X] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/models/train-model/advanced-settings/utils.ts [hunk 1]
```diff
@@ -16,17 +16,6 @@ import type {
 } from '../../../../constants/shared-types';
 import { isParameter, isParameterGroup } from '../../model-listing/model-training-parameters/utils';
 
-const getDecimalPoints = (value: number): number => {
```
Comment (dwesolow) [inline application/ui/src/features/models/train-model/advanced-settings/utils.ts:19]: these were duplicates

File: application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx [hunk 2]
```diff
@@ -1,88 +1,79 @@
...
-    const handleRangeChange = (inputValue: RangeValue<number>): void => {
-        const { start, end } = inputValue;
-        // Prevent start and end from being equal
-        if (end - start >= fieldStep) {
-            setDraftRange({ start, end });
-        }
-    };
-
     const handleNumberChange = (start: number, end: number): void => {
         // Prevent start and end from being equal
```
[the remark this answers is not in the document]
Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx]: updated

File: application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx [hunk 3]
```diff
@@ -1,88 +1,78 @@
...
+    minValue,
+    maxValue,
 }: RangeParameterFieldProps) => {
-    const [draftRange, setDraftRange] = useState<RangeValue<number> | null>(null);
-    const parameterValue = draftRange ?? { start: value[0], end: value[1] };
+    const [parameterValues, setParameterValues] = useState<RangeValue<number>>({ start: value[0], end: value[1] });
+    const prevValues = useRef<RangeParameterValue>(value);
 
-    const fieldStep = getStep({ step, maxValue: defaultValue[1], minValue: defaultValue[0] });
+    if (!isEqual(prevValues.current, value)) {
```
Comment (camiloHimura) [inline application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx:38]: why is this needed?

File: application/ui/src/features/models/train-model/advanced-settings/components/parameters.component.tsx [hunk 4]
```diff
@@ -287,7 +287,11 @@ const ParameterField = ({ parameter, onChange, isDisabled }: ParameterFieldProps
         return (
             <RangeParameterField
                 value={parameter.value}
-                defaultValue={parameter.default_value}
+                // TODO: Replace these two lines with `max_value` and `min_value`
```
Comment (camiloHimura) [inline application/ui/src/features/models/train-model/advanced-settings/components/parameters.component.tsx:290]: api update?

File: application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx (hunk 3 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx:38]: Same reason as before, to be able to sync state.

File: application/ui/src/features/models/train-model/advanced-settings/components/parameters.component.tsx (hunk 4 above)
Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/components/parameters.component.tsx:290]: Yes, backend PR is ready, I want to merge this PR and then update backend pr:
https://github.com/open-edge-platform/training_extensions/pull/6127

File: application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx [hunk 5]
```diff
@@ -1,88 +1,78 @@
...
         const { start, end } = inputValue;
 
-        setDraftRange(null);
+        setParameterValues(inputValue);
         onChange([start, end]);
     };
 
-    const handleRangeChange = (inputValue: RangeValue<number>): void => {
-        const { start, end } = inputValue;
-        // Prevent start and end from being equal
```
Comment (jpggvilaca) [inline application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx:53]: why do we not need this verification anymore?

Comment (dwesolow) [reply application/ui/src/features/models/train-model/advanced-settings/components/range-parameter-field/range-parameter-field.component.tsx:53]: because we mix `minValue` and `maxValue` on numberfield and slider components.

**Review by jpggvilaca — APPROVED** [review]
