### PR TITLE
Move subset assignment to annotation endpoint

### LINKED ISSUE #5891: Cannot assign subset to video frame
**Steps to reproduce**

1. Open a video frame
2. Annotate it
3. Try to manually assign a subset to the annotated frame

Image

**Expected**

A subset can be assigned to the frame

**Actual**

The request fails with a 404 Not Found error:
```
2026-03-24 11:53:44.375 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 127.0.0.1:39776 - "PATCH /api/projects/2d3280e3-2cb2-4b13-8f4a-dcaaed969678/dataset/items/d996a4b7-635c-4b9e-ac44-e53061654a3b/subset HTTP/1.1" 404
```

### PR DESCRIPTION
**Pull request by JortBergfeld**
In order to support subset assignment for video frames, we have to ensure that an annotation for a video frame is submitted before subset assignment, because video frames are only extracted and given a media_id (== dataset_item_id) after an annotation is created.

- Removed subset endpoint
- Added subset as an optional JSON body parameter to the annotation endpoint. If null, the current subset assignment is not changed.
- Updated annotation endpoint to first validate and create annotation (and extracting a video frame and saving it to disk), then to change the subset assignment
- Minor update to subset assignment logic: If given subset is the same as the already assigned subset, we no longer raise an error.  If another subset is already assigned,  we still raise an error.

Resolves #5891 

### How to test

Tests have been updated

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/dataset/media-preview/bottom-toolbar/bottom-toolbar.component.tsx [hunk 1]
```diff
@@ -26,40 +28,76 @@ type BottomToolbarProps = {
...
+            error: annotationsError,
+            response,
+        } = await fetchClient.GET('/api/projects/{project_id}/dataset/media/{media_id}/annotations', {
+            params: {
+                path: { project_id: projectId, media_id: mediaItem.id },
+                query,
+            },
+        });
+
+        if (annotationsError && response.status !== 404 && !isUnannotatedError(annotationsError)) {
```
Comment (dwesolow) [inline application/ui/src/features/dataset/media-preview/bottom-toolbar/bottom-toolbar.component.tsx]: if the logic in the `useAnnotationsQuery` change, this part will be outdated.

File: application/ui/src/features/dataset/media-preview/bottom-toolbar/bottom-toolbar.component.tsx [hunk 2]
```diff
@@ -26,40 +28,76 @@ type BottomToolbarProps = {
...
+        }
+
         updateSubsetMutation.mutate({
-            params: { path: datasetItemParamsPath },
-            body: { subset: key },
+            params: {
+                path: { project_id: projectId, media_id: mediaItem.id },
+                query,
+            },
+            body: { annotations: annotationsResponse?.annotations ?? [], subset: key },
```
Comment (dwesolow) [inline application/ui/src/features/dataset/media-preview/bottom-toolbar/bottom-toolbar.component.tsx]: why do we need to send annotations while updating the subset?
Server knows that media A has annotations XYZ so when we assign the subset server can just check annotations on their side, no?

Comment (dwesolow) [inline application/ui/src/features/dataset/media-preview/bottom-toolbar/bottom-toolbar.component.tsx]: Based on PR's description: what will happen if user draw an annotation and assigns a subset on the video frame, before submitting the annotations?

File: application/ui/src/features/dataset/media-preview/bottom-toolbar/bottom-toolbar.component.tsx (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/bottom-toolbar/bottom-toolbar.component.tsx]: Agree, leveraged the hook instead

**Review by camiloHimura — DISMISSED** [review]

File: application/ui/src/features/dataset/media-preview/use-submit-predictions.hook.ts [hunk 3]
```diff
@@ -0,0 +1,20 @@
+// Copyright (C) 2025-2026 Intel Corporation
```
Comment (dwesolow) [inline application/ui/src/features/dataset/media-preview/use-submit-predictions.hook.ts]: We no longer need this file, it was removed in https://github.com/open-edge-platform/training_extensions/pull/6013

**Review by camiloHimura — DISMISSED** [review]

**Review by camiloHimura — DISMISSED** [review]

**Review by itallix — DISMISSED** [review]

**Review by camiloHimura — APPROVED** [review]

**Review by itallix — APPROVED** [review]
