### PR TITLE
fix: Importing dataset annotation status

### LINKED ISSUE #6078: Importing dataset from the project dataset view renders wrong annotation status
**Describe the bug**

Annotated items are rendered with unannotated icons when importing dataset from the project dataset view.

**Steps to Reproduce**

1. Create a new project of any type
2. Import a dataset with annotated items from the project dataset view

**Actual:** items are rendered as unannotated
**Expected:** items are rendered as annotated

### PR DESCRIPTION
**Pull request by camiloHimura**
### Summary
closes #6078

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/dataset/import-export/import-jobs-list/import-jobs-list.component.tsx [hunk 1]
```diff
@@ -36,6 +36,14 @@ export const ImportJobsList = () => {
...
             ]),
         });
+
+        queryClient.invalidateQueries({
+            queryKey: getQueryKey([
+                'get',
+                '/api/projects/{project_id}/dataset/items',
+                { params: { path: { project_id: projectId } } },
+            ]),
+        });
```
Comment (dwesolow) [inline application/ui/src/features/dataset/import-export/import-jobs-list/import-jobs-list.component.tsx]: These are async operations. Do we want to use `handleImportSuccess` to keep `isPending` state of the caller? i.e. loading is false only when importing dataset and refetching both queries is finished.

Comment (camiloHimura) [reply application/ui/src/features/dataset/import-export/import-jobs-list/import-jobs-list.component.tsx]: yes, updated

File: application/ui/src/features/dataset/import-export/import-jobs-list/import-jobs-list.component.tsx [hunk 2]
```diff
@@ -28,14 +28,22 @@ export const ImportJobsList = () => {
...
+    const handleImportSuccess = async () => {
+        await queryClient.invalidateQueries({
             queryKey: getQueryKey([
                 'get',
                 '/api/projects/{project_id}/dataset/media',
                 { params: { path: { project_id: projectId } } },
             ]),
         });
+
+        await queryClient.invalidateQueries({
```
Comment (dwesolow) [inline application/ui/src/features/dataset/import-export/import-jobs-list/import-jobs-list.component.tsx]: we could speed up and use `await Promise.all([...])`, wdyt?

**Review by jpggvilaca — DISMISSED** [review]

File: application/ui/src/features/dataset/import-export/import-jobs-list/import-jobs-list.component.tsx (hunk 2 above)
Comment (camiloHimura) [reply application/ui/src/features/dataset/import-export/import-jobs-list/import-jobs-list.component.tsx]: great suggestion, updated

**Review by jpggvilaca — APPROVED** [review]

**Review by dwesolow — APPROVED** [review]
