### PR TITLE
fix: Labels management panel should not close on color's change

### LINKED ISSUE #6162: Cannot change color of newly added label
**Describe the bug**

* Selecting a label color closes the label editing dialog

**Steps to Reproduce**

1. Go to annotator page
2. Open the label list on the top
3. Press + to create a new label
4. Press the color picker and select any color

Dialog closes, label is not added

**Environment:**

- OS: 
- Framework version: 
- Python version:
- OpenVINO version:
- CUDA/cuDNN version:
- GPU model and memory:

### PR DESCRIPTION
**Pull request by dwesolow**
### Summary

The issue was that `CustomPopover` uses `useOnClickOutside` that closed that dialog whenever mouse is released on color picker. Now we use popover from spectrum directly so that is save and works fine.

Fix #6162 

### Checklist

- [X] The PR title and description are clear and descriptive
- [X] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/annotator/labels/labels-editor/labels-editor-popover.component.tsx [hunk 1]
```diff
@@ -1,25 +1,39 @@
...
+};
+
+const LabelEditorPopover = ({ triggerRef, state, children }: LabelEditorPopoverProps) => {
+    return (
+        <Popover
+            hideArrow
+            triggerRef={triggerRef}
+            state={state}
+            placement={'bottom end'}
+            UNSAFE_style={{
```
Comment (jpggvilaca) [inline application/ui/src/features/annotator/labels/labels-editor/labels-editor-popover.component.tsx:28]: why do we need this transform?

**Review by jpggvilaca — APPROVED** [review]

**Review by camiloHimura — APPROVED** [review]

File: application/ui/src/features/annotator/labels/labels-editor/labels-editor-popover.component.tsx (hunk 1 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/labels/labels-editor/labels-editor-popover.component.tsx:28]: without this popover overlaps the button a bit
