### PR TITLE
fix: number of media items

### LINKED ISSUE #6180: Reported number of media is wrong
**Steps to reproduce**

1. Import a relatively large dataset, e.g. [this](http://storage.geti.intel.com/test-data/geti/datasets/qa/fire-coco-medium.zip)
2. Open the project and check the media counter reported in the top-right corner
3. Scroll down the list of dataset items

**Expected**

The counter reports the number of images (and maybe videos?) in the dataset. It doesn't change unless media are uploaded or deleted.

**Actual**

The counter is updated as the UI loads more items; from user perspective, it's misleading.

Image

### PR DESCRIPTION
**Pull request by camiloHimura**
### Summary

This PR moves all dataset filter–related information to the URL, including label and status. It displays both the total number of items and the number of filtered items. It uses “medias” to represent all items without distinguishing between images and videos, this may be supported in the future.

| Total items  | Total filtered items |
| ------------- | ------------- |
| image | Screenshot 2026-04-23 at 12 14 28 |

Closes #6180

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/dataset/gallery/toolbar/filter-by-status/filter-by-status.component.tsx [hunk 1]
```diff
@@ -18,14 +13,16 @@ const FILTER_BY_STATUS_OPTIONS: { name: string; key: FilterByStatusKey }[] = [
...
+    const { annotationStatus, setAnnotationStatus } = useDatasetFiltersSearchParams();
+
     return (
         <Picker
             maxWidth='size-3000'
             aria-label={'media status'}
             items={FILTER_BY_STATUS_OPTIONS}
-            defaultSelectedKey={FILTER_BY_STATUS_OPTIONS[0].key}
-            onSelectionChange={(status) => onChange(status as FilterByStatusKey)}
+            defaultSelectedKey={annotationStatus ?? FILTER_BY_STATUS_OPTIONS[0].key}
```
Comment (dwesolow) [inline application/ui/src/features/dataset/gallery/toolbar/filter-by-status/filter-by-status.component.tsx]: if this is controlled `selectedKey` should be used instead of `defaultSelectedKey`

File: application/ui/src/features/dataset/gallery/toolbar/total-items.test.tsx [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+import { getMockedMediaImage } from 'mocks/mock-media';
+import { HttpResponse } from 'msw';
+import { render } from 'test-utils/render';
+
+import { http } from '../../../../api/utils';
+import { server } from '../../../../msw-node-setup';
+import { TotalItems } from './total-items.component';
+
+vi.mock('hooks/use-project-identifier.hook', () => ({
+    useProjectIdentifier: () => 'project-123',
```
Comment (dwesolow) [inline application/ui/src/features/dataset/gallery/toolbar/total-items.test.tsx]: we should not mock `useProjectIdentifier`, let's user `render` options parameter to set correct project id route

File: application/ui/src/hooks/use-dataset-filters-search-params.hook.test.ts [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+
+        expect(result.current.selectedLabelIds).toEqual(newLabels);
+    });
+
+    it('clears filter param when setting empty ids', () => {
+        const labelName = 'id-1';
+        const encoded = encodeFilterSearchParam(labelName);
+
+        const { result } = renderHook(() => useDatasetFiltersSearchParams(), {
+            route: `/projects/123?filtersFiler=${encoded}`,
```
Comment (dwesolow) [inline application/ui/src/hooks/use-dataset-filters-search-params.hook.test.ts]: typo? `filtersFiler`

File: application/ui/src/hooks/use-dataset-filters-search-params.hook.ts [hunk 4]
```diff
@@ -1,13 +1,24 @@
...
 import { parse, stringify } from 'zipson/lib';
 
+import type { DatasetItemAnnotationStatus, FilterByStatusKey } from '../constants/shared-types';
 import { isNonEmptyString } from '../shared/util';
 
-const LABELS_PARAM = 'filters';
+const LABELS_PARAM = 'filtersFiler';
+const ANNOTATION_STATUS_PARAM = 'annotationStatusFilter';
+
+const VALID_ANNOTATION_STATUSES: Set<string> = new Set<string>(['unannotated', 'reviewed', 'to_review']);
```
Comment (dwesolow) [inline application/ui/src/hooks/use-dataset-filters-search-params.hook.ts]: it's brittle type, could we use types provided by the backend? if they add a new status, we would need to remember to update this.

Comment (camiloHimura) [reply application/ui/src/hooks/use-dataset-filters-search-params.hook.ts]: The backend provides the type, not the actual array list, so we need to update it manually. Also, if there’s any change, TypeScript will notify us that an update is needed. Since this doesn’t change often, it shouldn’t be an issue.

File: application/ui/src/features/dataset/gallery/toolbar/filter-by-status/filter-by-status.component.tsx (hunk 1 above)
Comment (camiloHimura) [reply application/ui/src/features/dataset/gallery/toolbar/filter-by-status/filter-by-status.component.tsx]: good point, updated

File: application/ui/src/features/dataset/gallery/toolbar/total-items.test.tsx (hunk 2 above)
Comment (camiloHimura) [reply application/ui/src/features/dataset/gallery/toolbar/total-items.test.tsx]: updated

File: application/ui/src/hooks/use-dataset-filters-search-params.hook.test.ts (hunk 3 above)
Comment (camiloHimura) [reply application/ui/src/hooks/use-dataset-filters-search-params.hook.test.ts]: yes, final name is `labelsFiler`, updated

File: application/ui/src/hooks/use-dataset-filters-search-params.hook.ts [hunk 5]
```diff
@@ -1,13 +1,25 @@
...
-import { isEmpty } from 'lodash-es';
+import { isEmpty, isNil } from 'lodash-es';
 import { useSearchParams } from 'react-router-dom';
 import { parse, stringify } from 'zipson/lib';
 
+import type { DatasetItemAnnotationStatus, FilterByStatusKey } from '../constants/shared-types';
 import { isNonEmptyString } from '../shared/util';
 
-const LABELS_PARAM = 'filters';
+export const LABELS_PARAM = 'labelsFiler';
```
Comment (jpggvilaca) [inline application/ui/src/hooks/use-dataset-filters-search-params.hook.ts:11]:
```suggestion
export const LABELS_PARAM = 'labelsFilter';
```

File: application/ui/src/features/dataset/gallery/toolbar/total-items.component.tsx [hunk 6]
```diff
@@ -0,0 +1,19 @@
+// Copyright (C) 2025 Intel Corporation
+// SPDX-License-Identifier: Apache-2.0
+
+import { Text } from '@geti/ui';
+import { useDatasetMediaWithReviewStatus } from 'hooks/use-dataset-media-with-review-status.hook';
+
+interface TotalItemsProps {
```
Comment (jpggvilaca) [inline application/ui/src/features/dataset/gallery/toolbar/total-items.component.tsx:7]: np: 

```suggestion
type TotalItemsProps {
```

**Review by jpggvilaca — APPROVED** [review]

File: application/ui/src/features/dataset/gallery/toolbar/total-items.component.tsx (hunk 6 above)
Comment (camiloHimura) [reply application/ui/src/features/dataset/gallery/toolbar/total-items.component.tsx:7]: I'll handle on my next PR

File: application/ui/src/hooks/use-dataset-filters-search-params.hook.ts (hunk 5 above)
Comment (camiloHimura) [reply application/ui/src/hooks/use-dataset-filters-search-params.hook.ts:11]: I'll handle on my next PR
