### PR TITLE
Hiding annotations should also hide anchors from selected annotation

### LINKED ISSUE #6067: Hide annotation tool does not work for latest annotation
1. Create a segmentation or detection project, upload images.
2. Go to Annotate
3. Create two annotations.
4. Click the Hide annotation icon

Detection:
the annotation is hidden but its small rectangle "corners" are still visible

Segmentation:
Previous annotation is hidden. The one added as the last is still shown.

### PR DESCRIPTION
**Pull request by jpggvilaca**
### Summary

* Closes https://github.com/open-edge-platform/training_extensions/issues/6067

### Checklist

- [ ] The PR title and description are clear and descriptive
- [ ] I have manually tested the changes
- [ ] All changes are covered by automated tests
- [ ] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/annotator/annotations/editable-annotation.component.tsx [hunk 1]
```diff
@@ -18,16 +19,19 @@ export const EditableAnnotation = ({ children }: EditAnnotationProps) => {
     const { scale } = useZoom();
     const annotation = useAnnotation();
     const { selectedAnnotations } = useSelectedAnnotations();
+    const { isVisible } = useAnnotationVisibility();
 
     const isSelected = selectedAnnotations.has(annotation.id);
+    const shouldDisplayEditAnchors = isVisible && isSelected && selectedAnnotations.size === 1;
 
-    if (isSelected && selectedAnnotations.size === 1) {
+    if (shouldDisplayEditAnchors) {
```
Comment (dwesolow) [inline application/ui/src/features/annotator/annotations/editable-annotation.component.tsx:27]: what about adding test for this?

**Review by dwesolow — DISMISSED** [review]

File: application/ui/src/features/annotator/annotations/editable-annotation.component.tsx (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/editable-annotation.component.tsx:27]: Agree, added

File: application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+let mockSelectedAnnotations = new Set<string>();
+
+vi.mock('../../../shared/annotator/select-annotation-provider.component', () => ({
+    useSelectedAnnotations: () => ({
+        selectedAnnotations: mockSelectedAnnotations,
+        setSelectedAnnotations: vi.fn(),
+    }),
+}));
+
+let mockIsVisible = true;
```
Comment (dwesolow) [inline application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx]: could we move mocking `useAnnotationVisibility` to be inside `renderWithAnnotation` and pass `mockIsVisible` as a prop there? Right now to read the test I need to scroll up/down to see where the things are defined. (same with `mockSelectedAnnotations`)

File: application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+    it('renders EditBoundingBox anchors when a rectangle annotation is selected and visible', async () => {
+        mockSelectedAnnotations = new Set([rectangleAnnotation.id]);
+
+        await renderWithAnnotation(rectangleAnnotation);
+
+        expect(screen.getByLabelText(`Edit bounding box points ${rectangleAnnotation.id}`)).toBeInTheDocument();
+        expect(screen.queryByTestId(CHILD_TEST_ID)).not.toBeInTheDocument();
+    });
+
+    it('renders EditPolygon when a polygon annotation is selected and visible', async () => {
```
Comment (dwesolow) [inline application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx:141]: IMO this one should be combines with `renders EditBoundingBox anchors when a rectangle annotation is selected and visible`

**Review by camiloHimura — DISMISSED** [review]

File: application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx (hunk 3 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx:141]: I think in here i'd rather be explicit

File: application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx (hunk 2 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx]: Updated. But we still need the variables since we're using them on the mocks

Comment (dwesolow) [reply application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx]: Mocks can be also moved to render function `vi.mocked(...)`.

Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotations/editable-annotation.component.test.tsx]: Indeed, updated

**Review by dwesolow — APPROVED** [review]
