### PR TITLE
fix: Prediction loading and buffering

### LINKED ISSUE #6184: User gets no feedback while waiting for prediction in annotator
**Steps to reproduce**

1. Train a model
2. Open an unannotated image in Prediction mode

**Expected**

Predictions are generated on-the-fly and displayed on the canvas. If it takes a while to load the prediction, the UI should display a loading icon or similar, i.e. something that informs the user to wait a few seconds for the prediction.

**Actual**

There is no visual effect to tell the user to wait; the UI displays the image without annotations for several seconds, which is confusing for the user ("Is there no prediction? Did I do anything wrong?")

Image

### PR DESCRIPTION
**Pull request by dwesolow**
### Summary

1. Add loading overlay while waiting for predictions to be returned from the server.
2. Play/pause video automatically while we're waiting for the predictions.
3. Fix disable state of the submit button.
4. Disabled models picker when video is playing or predictions are loading.
5. Prefetch annotations.

Fix #6184 

### Checklist

- [X] The PR title and description are clear and descriptive
- [X] I have manually tested the changes
- [X] All changes are covered by automated tests
- [X] All related issues are linked to this PR (if applicable)
- [ ] Documentation has been updated (if applicable)

### CODE REVIEW

File: application/ui/src/features/dataset/media-preview/utils.ts [hunk 1]
```diff
@@ -119,3 +119,29 @@ export const useAnnotatorMode = ({
 
     return [mode, setMode] as const;
 };
+
+export const usePlayPauseVideoBySystem = (isLoadingPredictions: boolean) => {
+    const isPausedBySystem = useRef<boolean>(false);
+    const context = useVideoPlayerContext();
+
+    const playRef = useRef(context?.videoControls.play);
```
Comment (camiloHimura) [inline application/ui/src/features/dataset/media-preview/utils.ts:127]: Why add an extra ref instead of calling the handlers directly?

Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:127]: Because they are not memoized so they would cause triggering the `useEffect`. Will be replaced once we move to next react version https://github.com/open-edge-platform/training_extensions/pull/6128

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx [hunk 2]
```diff
@@ -79,6 +80,21 @@ const ImageAnnotations = ({ mediaItem }: ImageAnnotationsProps) => {
     );
 };
 
+const PrefetchAnnotations = () => {
+    const { videoFrame, step } = useVideoPlayer();
+
+    const nextFrameRangeIndexes = getVideoFrameRangeIndexes({
```
Comment (jpggvilaca) [inline application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:86]:
```suggestion
    const frameRangeIndexes = getVideoFrameRangeIndexes({
    
    or
    
    const { endFrameIndex } = ...
```

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx [hunk 3]
```diff
@@ -79,6 +80,21 @@ const ImageAnnotations = ({ mediaItem }: ImageAnnotationsProps) => {
...
+        frames: videoFrame.frame_count - 1,
+        frameSkip: step,
+        frameNumber: videoFrame.frame_number,
+    });
+
+    usePrefetchVideoFramesAnnotations({ frameNumber: videoFrame.frame_number, frameSkip: step });
```
Comment (jpggvilaca) [inline application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:92]: this is a bit misleading since it actually fetches the current frame. This should live outside of this "prefetch" method. Or we rename it

File: application/ui/src/features/annotator/api/use-media-predictions.ts [hunk 4]
```diff
@@ -71,3 +75,15 @@ export const useMediaPredictions = ({
 
     return useQuery(mediaPredictionsQueryOptions({ projectId, modelId, mediaId, range }));
 };
+
+export const useIsLoadingAnyPredictions = (mediaId: string) => {
```
Comment (jpggvilaca) [inline application/ui/src/features/annotator/api/use-media-predictions.ts]:
```suggestion
export const useIsFetchingPredictions = (mediaId: string) => {
```

File: application/ui/src/features/annotator/api/use-media-predictions.ts [hunk 5]
```diff
@@ -71,3 +75,15 @@ export const useMediaPredictions = ({
...
+    const projectId = useProjectIdentifier();
+
+    const queryKey = MEDIA_PREDICTIONS_QUERY_KEY_PREFIX(projectId, mediaId);
+
+    return (
+        useIsFetching({
```
Comment (jpggvilaca) [inline application/ui/src/features/annotator/api/use-media-predictions.ts]: np: move this to a variable because some engineers might not know what that hook does

File: application/ui/src/features/annotator/video-player/video-toolbar/video-controls.component.tsx [hunk 6]
```diff
@@ -4,13 +4,21 @@
...
+type VideoControlsProps = {
+    mode: AnnotatorMode;
+};
+
+export const VideoControls = ({ mode }: VideoControlsProps) => {
+    const { isMuted, toggleMute, videoControls, videoFrame } = useVideoPlayer();
     const { isPlaying, play, pause, previousFrame, nextFrame, canSelectPreviousFrame, canSelectNextFrame } =
         videoControls;
 
+    const isLoadingPredictions = useIsLoadingAnyPredictions(videoFrame.id) && mode === 'prediction';
```
Comment (jpggvilaca) [inline application/ui/src/features/annotator/video-player/video-toolbar/video-controls.component.tsx]: can we not `const { mode } = useAnnotator()` from within `useIsLoadingAnyPredictions`?

File: application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx [hunk 7]
```diff
@@ -47,6 +48,8 @@ type SecondaryToolbarProps = {
     onModeChange: (mode: AnnotatorMode) => void;
     onSelectNextMediaItem: () => void;
     subset: DatasetSubset;
+    isSubsetChanged: boolean;
```
Comment (jpggvilaca) [inline application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx]: np:
```suggestion
    hasSubsetChanged or didSubsetChange
```

File: application/ui/src/features/dataset/media-preview/annotator.component.tsx [hunk 8]
```diff
@@ -78,8 +79,14 @@ const Annotator = ({
     onSelectedMediaItem,
     onChangeAnnotatorMode,
 }: AnnotatorProps) => {
+    const isAnnotationMode = mode === 'annotation';
+    const isPredictionMode = mode === 'prediction';
+
     const { nextMediaItem } = useNextMediaPrefetch(mediaItem, items);
     const { currentSubset, changeCurrentSubset, isReadOnlySubset } = useSubset(subset, mediaItem);
+    const isLoadingPredictions = useIsLoadingAnyPredictions(mediaItem.id) && isPredictionMode;
```
Comment (jpggvilaca) [inline application/ui/src/features/dataset/media-preview/annotator.component.tsx]: same as above

File: application/ui/src/features/dataset/media-preview/annotator.component.tsx [hunk 9]
```diff
@@ -129,7 +135,8 @@ const Annotator = ({
                 />
             </View>
 
-            <View gridArea={'canvas'} overflow={'hidden'}>
+            <View gridArea={'canvas'} overflow={'hidden'} position={'relative'}>
+                {isLoadingPredictions && <Loading mode={'overlay'} />}
```
Comment (jpggvilaca) [inline application/ui/src/features/dataset/media-preview/annotator.component.tsx:139]: did u try mode='inline'?  so then u dont need the relative position. (i havent tested tho)

File: application/ui/src/features/dataset/media-preview/utils.ts (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/utils.ts:127]: Would it help to wrap video controls methods in useCallback?

File: application/ui/src/features/dataset/media-preview/utils.ts [hunk 10]
```diff
@@ -119,3 +119,29 @@ export const useAnnotatorMode = ({
...
+
+    useEffect(() => {
+        pauseRef.current = context?.videoControls.pause;
+    }, [context?.videoControls.pause]);
+
+    useEffect(() => {
+        if (isLoadingPredictions && context?.videoControls.isPlaying) {
+            isPausedBySystem.current = true;
+            pauseRef.current?.();
+        } else if (!isLoadingPredictions && isPausedBySystem.current) {
```
Comment (jpggvilaca) [inline application/ui/src/features/dataset/media-preview/utils.ts:142]: should we play automatically after we stop loading? I think we will always be loading, or at least the buffer should keep going, just like youtube. Even after you buffer for long enoufgh and you have "a few" predictions, the user might want to wait for it to load more, instead of buffering-autoplay and 2 seconds later you buffer again. tl;dr: we should not autoplay after we stop loading, let the user do that

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx (hunk 2 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:86]: Why? I want this to be obvious that we want to get next indexes, not current.

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx (hunk 3 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:92]: It does not fetch annotations for the current range, it uses `usePrefetchQuery` so it only prefetches (adds to the cache so when `useQuery` is called it will use cache).

File: application/ui/src/features/dataset/media-preview/annotator.component.tsx (hunk 9 above)
Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/annotator.component.tsx:139]: No because I what I want is to display overlay on top of the canvas, not inline the loading spinner.

File: application/ui/src/features/dataset/media-preview/utils.ts (hunk 10 above)
Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: I don't agree that would be really stupid behavior: system decides to pause but wants the user decide to play.
We prefetch a lot of frames before so if the inference server is improved that would not be the issue (i.e. should not happen that video paused, fetched, played and paused again 2 seconds later).

Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: The pause should happen as you implemented (correct logic), but the play imho should not happen automatically. You can stop fetching/loading once we have predictions but we should not play automatically, or else it's gonna be like watching a video with 3G connection

File: application/ui/src/features/dataset/media-preview/annotator.component.tsx (hunk 9 above)
Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/annotator.component.tsx:139]: okay

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx (hunk 2 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:86]: isnt the first fetch fetching the current one?

Comment (dwesolow) [reply application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:86]: `usePrefetchVideoFramesAnnotations({ frameNumber: videoFrame.frame_number, frameSkip: step });` -> first fetch
`usePrefetchVideoFramesAnnotations({ frameNumber: nextFrameRangeIndexes.endFrameIndex + 1, frameSkip: step });` -> next fetch

File: application/ui/src/features/dataset/media-preview/utils.ts (hunk 10 above)
Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: on yt, when it pauses, does it play or keep being in pause?

Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: without the play for me that feature is implemented in 50%

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx (hunk 3 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:92]: i understand is PREfetching and not fetching but i meant that it's a bit weird that the prefetch component prefetches the current  frame and the next. For me the prefetch should happen for the next frame(s), not current, for the current you use `useQuery`. But not a big deal

File: application/ui/src/features/dataset/media-preview/utils.ts (hunk 1 above)
Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:127]: yeah but I didn't want to touch video controls, if u want i can change it there

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx (hunk 3 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:92]: When u have annotator with the video, what we do is we fetch annotations for the frame. This code is responsible for fetching annotations while playing a video. So to improve that, when video is paused (frame is displayed) we want to prefetch so whenever video starts playing there are already annotations.

File: application/ui/src/features/annotator/api/use-media-predictions.ts (hunk 4 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/api/use-media-predictions.ts]: updated

File: application/ui/src/features/annotator/video-player/video-toolbar/video-controls.component.tsx (hunk 6 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/video-player/video-toolbar/video-controls.component.tsx]: We don't have `useAnnotator` and we don't have `mode` in the provider as well. Once we add that mode to the URL then we can move that `mode` to be inside `useIsLoadingAnyPredictions`

File: application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx (hunk 7 above)
Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/secondary-toolbar/secondary-toolbar.component.tsx]: Updated

File: application/ui/src/features/annotator/api/use-media-predictions.ts (hunk 5 above)
Comment (dwesolow) [reply application/ui/src/features/annotator/api/use-media-predictions.ts]: Then they should check docs 😄.
Updated

File: application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx (hunk 3 above)
Comment (jpggvilaca) [reply application/ui/src/features/annotator/annotator-canvas/annotator-canvas.tsx:92]: i see

File: application/ui/src/features/dataset/media-preview/utils.ts (hunk 1 above)
Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/utils.ts:127]: this is fine, just wondering

File: application/ui/src/features/dataset/media-preview/utils.ts (hunk 10 above)
Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: We just need to think in terms of UX. My reasoning came from the following scenario:
1) User presses play, video plays for like 3 seconds
2) On second 3, it pauses because we are fetching predictions
3) User waits for a few seconds, then the video automatically plays (we got the predictions back)
4) After 1 or 2 more seconds, pause again. Repeat 2-3

It will feel clunky and slow. If we let the user control the play, we can load more predictions. Usually users prefer to pause and wait then to play and the video stopping everytime.

Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: Yeah I understand that but step 1 should never happen that is my point

Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: wdym? user never presses player ever?

Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: We should always get predictions for longer period than 3 seconds, in other scenario our feature is not usable.
I can remove resuming, but I'm more than sure that we will be requested to add it back.

Comment (jpggvilaca) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: If we can guarantee at least >= 5 seconds of stable video with predictions then this is fine

**Review by jpggvilaca — APPROVED** [review]

File: application/ui/src/features/dataset/media-preview/utils.ts (hunk 10 above)
Comment (dwesolow) [reply application/ui/src/features/dataset/media-preview/utils.ts:142]: Let agree on this: if inference server is bad that when play pause play pause then I totally agree that we should not resume automatically. Let's come back to this once inference server is imporved.
